Repository werf/website, pull requests merged in 2023-06, with the labels that each got.

#638 ci: show the latest documentation in a menu
  _data/en/topnav.yml
  _data/ru/topnav.yml
  _includes/_common/channel-menu.html
  backend/common.go
  backend/handlers.go
  backend/main.go
Labels: scope: site

#650 site: update versioning logic
  _data/en/topnav.yml
  _includes/_common/channel-menu-v2.html
  _includes/_common/group-menu-v2.html
  assets/css/docs.css
  backend/common.go
  backend/main.go
  robots.txt
  ssi/channel-menu-v2.html
  ssi/group-menu-v2.html
Labels: test website, scope: site

#651 site: fix topnav
  _data/ru/topnav.yml
Labels: scope: site

#635 feat(configurator/argocd): new configurator scenario for ArgoCD integration
  bin/configurator/config.yml
  bin/configurator/static/_data/_common/configurator.yaml
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/docker-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/docker-runner/linux/buildah/project.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/buildah/project.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/docker/infra.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/docker/project.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/kubernetes-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/en/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/kubernetes-runner/linux/buildah/project.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/docker-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/docker-runner/linux/buildah/project.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/buildah/project.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/docker/infra.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/host-runner/linux/docker/project.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/kubernetes-runner/linux/buildah/infra.md.liquid
  bin/configurator/static/_includes/ru/configurator/tab/ci/argocd-with-gitlab-ci-cd/simple/kubernetes-runner/linux/buildah/project.md.liquid
Labels: test website

#662 Add new EN publiction
  _data/en/publications.yml
  assets/images/publications/en_150623.png
  pages_en/index.md
  pages_ru/index.md
Labels: test website
