Repository werf/website, pull requests merged in 2024-01, with the labels that each got.

#708 ci: use enterprise runners
  .github/workflows/cleanup.yml
  .github/workflows/content_validation.yml
  .github/workflows/deploy.yml
Labels: test website, scope: site

#713 Fixed twitter icon
  _includes/_common/topnav.html
  assets/css/index.css
  pages_en/index.md
  pages_ru/index.md
Labels: test website

#715 ci: Trigger Deploy on workflow_dispatch events
  .github/workflows/deploy.yml
Labels: scope: site
